# Default values for wordpress-managed-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  wordpress:
    repository: wordpress
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

storage:
  wordpress:
    storageClassName: ""
    StorageSize: "1G"

service:
  wordpress:
    type: ClusterIP
    port: 80

External_MySQL:
  IP: ""
  Port: 3306
  Password: ""

