apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-external-db-{{ .Release.Name }}
subsets:
  - addresses:
      - ip: {{ required "The IP address of the external MySQL DB" .Values.External_MySQL.IP }}
    ports:
      - port: {{ .Values.External_MySQL.Port }}