# kubectl create secret generic wp-mysql-external-password --from-literal=mysql_user_password=password22
apiVersion: v1
kind: Secret
metadata:
  name: wp-mysql-external-password-{{ .Release.Name }}
data:
  mysql_user_password: {{ required "The password of the external MySQL DB" .Values.External_MySQL.Password }} # echo 'password22' | base64
